name: Create a new release

on:
  push:
    branches:
      - master

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

      - name: Install dependencies
        run: |
          go mod download

      - name: Build binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -o bin/gosh-darwin
          GOOS=linux GOARCH=amd64 go build -o bin/gosh-linux
          GOOS=windows GOARCH=amd64 go build -o bin/gosh.exe
  release:
    outputs:
      release_version: ${{steps.semantic.outputs.new_release_version}}
    needs:
      - build-binaries
    runs-on: ubuntu-latest
    container:
      image: node:12.18.1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install conventional-changelog-conventionalcommits
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}